server:
  # Configuration of Spring Boot embedded Tomcat server (java -jar movierama.war)
  servlet:
    contextPath: '/movierama'
  port: 8443
  http:
    port: 8080
endpoints:
  jmx:
    domain: movierama
logging:
  config: 'classpath:movierama-logback.xml'
spring:
  jmx:
    default-domain: movierama
  data:
    rest:
      defaultMediaType: application/json
  jpa:
    generate-ddl: true
    show-sql: true
    #hibernate:
      #ddl-auto: create-drop # create | update | validate | create-drop
    properties:
      net.sf.ehcache.configurationResourceName: movierama-ehcache.xml
      hibernate:
        default_schema: movierama
        show_sql: false
        generate_statistics: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
  datasource:
    url: 'jdbc:postgresql://rdbms:5432/movierama?currentSchema=movierama'
    username: movierama
    password: movierama
    driver-class-name: org.postgresql.Driver
flyway:
  enabled: true
  table: DB_MIGRATION_HISTORY
  sqlMigrationSuffix: .sql
  schemas: movierama
application:
  roles:
    admin:
      access-token: admin # Change in PRD with a UUID